package ytdlp

import (
	"errors"
	"net/url"
	"regexp"
	"strings"
)

// ErrNotYouTube is returned for anything this package will not accept.
//
// The parser is deliberately strict rather than passing whatever was typed
// through to yt-dlp, which understands hundreds of sites. Recognising only what
// the button advertises means the failure is a sentence the user can act on,
// and widening it later is a change to this one file.
var ErrNotYouTube = errors.New("that does not look like a YouTube link")

// Link is a YouTube address this app knows how to queue.
type Link struct {
	// VideoID is empty for a link that names only a playlist.
	VideoID string

	// PlaylistID is empty for a link that names only a video. A "Share" link
	// copied while watching inside a playlist carries both.
	PlaylistID string
}

// IsPlaylist reports whether the link names a playlist, and so may expand to
// many tracks.
func (l Link) IsPlaylist() bool { return l.PlaylistID != "" }

// WatchURL is the canonical address of a single video.
func (l Link) WatchURL() string {
	return "https://www.youtube.com/watch?v=" + l.VideoID
}

// ListingURL is the address to ask yt-dlp to enumerate.
//
// A link carrying both a video and a playlist keeps both: an autogenerated mix
// (a list id beginning RD) exists only in the context of the video it was
// started from, and asking for it on its own returns nothing.
func (l Link) ListingURL() string {
	switch {
	case l.VideoID != "" && l.PlaylistID != "":
		return "https://www.youtube.com/watch?v=" + l.VideoID + "&list=" + l.PlaylistID
	case l.PlaylistID != "":
		return "https://www.youtube.com/playlist?list=" + l.PlaylistID
	default:
		return l.WatchURL()
	}
}

var (
	// Video ids are exactly eleven characters of YouTube's base64 alphabet.
	videoIDRe = regexp.MustCompile(`^[A-Za-z0-9_-]{11}$`)

	// Playlist ids vary in length and prefix far more than video ids do, so
	// this only insists on the alphabet.
	playlistIDRe = regexp.MustCompile(`^[A-Za-z0-9_-]{2,100}$`)
)

// hosts that serve the same content under different front ends.
var youtubeHosts = map[string]bool{
	"youtube.com":       true,
	"www.youtube.com":   true,
	"m.youtube.com":     true,
	"music.youtube.com": true,
	"youtu.be":          true,
	"www.youtu.be":      true,
}

// pathPrefixes carrying a video id as the next path segment.
var videoPathPrefixes = []string{"shorts", "live", "embed", "v"}

// ParseLink recognises a YouTube address and pulls the ids out of it.
//
// It accepts what a browser or the Share button actually produces, including a
// bare host with no scheme, which is what a copy out of an address bar often
// looks like.
func ParseLink(raw string) (Link, error) {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return Link{}, ErrNotYouTube
	}

	// A missing scheme parses as a path rather than a host, so one is supplied
	// before anything else looks at the result.
	if !strings.Contains(raw, "://") {
		raw = "https://" + raw
	}

	parsed, err := url.Parse(raw)
	if err != nil {
		return Link{}, ErrNotYouTube
	}
	if parsed.Scheme != "http" && parsed.Scheme != "https" {
		return Link{}, ErrNotYouTube
	}
	if !youtubeHosts[strings.ToLower(parsed.Hostname())] {
		return Link{}, ErrNotYouTube
	}

	query := parsed.Query()
	link := Link{VideoID: query.Get("v")}

	if list := query.Get("list"); playlistIDRe.MatchString(list) {
		link.PlaylistID = list
	}

	segments := strings.FieldsFunc(parsed.Path, func(r rune) bool { return r == '/' })

	// youtu.be/<id> puts the video in the first path segment; every other host
	// spells the form out, as /shorts/<id> or /live/<id>.
	if link.VideoID == "" && len(segments) > 0 {
		switch {
		case strings.EqualFold(parsed.Hostname(), "youtu.be") || strings.EqualFold(parsed.Hostname(), "www.youtu.be"):
			link.VideoID = segments[0]
		case len(segments) > 1 && contains(videoPathPrefixes, strings.ToLower(segments[0])):
			link.VideoID = segments[1]
		}
	}

	if !videoIDRe.MatchString(link.VideoID) {
		link.VideoID = ""
	}
	if link.VideoID == "" && link.PlaylistID == "" {
		return Link{}, ErrNotYouTube
	}
	return link, nil
}

func contains(values []string, want string) bool {
	for _, v := range values {
		if v == want {
			return true
		}
	}
	return false
}
